services:
  - type: web
    name: bug-tracker
    runtime: java
    buildCommand: "./mvnw clean package -DskipTests"
    startCommand: "java -jar target/bug-tracker-0.0.1-SNAPSHOT.jar"
    plan: free
